language: node_js
node_js:
- '8'
script:
- npm run unit
- npm run build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: qC/2e71rqHjWi5H6oH1n0dFwf0P974sIFzk1FVHU2sa/f2KQfIZSexbMF9XfUlvNOAbnHyBaF28rwUZcTR1SD/grXhcHKiJge0qhyldbB+5GfjTep/NMN9EWVyCXEEYY9/bVqqfUHAoTR2seTKTuMZSXQ8aIbJ3g14KTO5QGPOVKcJL0UEnq6I4g4nWgUNz0q33R8uu9bkCijeuQwjdkjARl3GKlyZQa1le6F0y64Q2+K5xleNV88FRk5+NgKNFdeqTjLHguzrxoSGMZ6ckw5m2ZXIv1fjdF5PFg63cNBxcLzbcfqXv6rVB44y8f9tQoS19QY01VC08ekpJ+mDd6c9v3gS5Qq5xHtGrKZ/5zGuXIrYj8YiUB4dXOPppRWepSOlVx+pLJBIbMqohXsgALOrBu78RdT8BwyeOTgPSF1EUvZneEfC8Z2dMvnwUjpT8DtmSEuuixu0TTUeecgKsZB//Ti73AJWXqOtIJcOFh6Lv+ZBq30N/PBM5bXfNDfJkNHFIf8br7dK5YyQSQJlOwIINckcjOQAdoRmkh+ByE1gjzjarm9MejA3NGdAefSac85i/vEeH02NZE8F7+G8tEe6uHnYtCua7mhCK80Zu5UTrMXJxRCYSmpyvWAaOoz2iSAtBWnzAnOmLmP1WjUNCcNzFWjY07Cf5miS7B8E0u9fM=
  project: "perclip-b465a"
